# Generated by Django 5.1 on 2025-01-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='restrictions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='type',
            field=models.CharField(choices=[('ON STREET', 'On Street'), ('OFF STREET', 'Off Street')], default='ON STREET', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ATTENDANTS', 'Attendants'), ('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=50),
        ),
    ]
