# Generated by Django 5.1 on 2025-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_parkinglot_restrictions_alter_parkinglot_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='subscription',
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_payment',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
