# Generated by Django 5.1 on 2025-01-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_ticket_duration_remove_ticket_parking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.BooleanField(default=False, max_length=50),
        ),
    ]
