# Generated by Django 5.1 on 2025-01-16 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ticket_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_spaces', to='app.parkinglot'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='parking_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.parkingspace'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
