# Generated by Django 5.1 on 2025-01-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_parkingspace_parking_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
