# Generated by Django 5.1 on 2025-01-17 07:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ticket_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Plate number needd to be formated like AAA 000 A', regex='^[A-Z]{3} [0-9]{3} [A-Z]$')])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Start date and time of the subscription.')),
                ('end_date', models.DateTimeField(help_text='End date and time of the subscription.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current status of the subscription.', max_length=20)),
                ('payment_status', models.BooleanField(default=False, help_text='Payment status: Paid or Not Paid.')),
                ('total_cost', models.IntegerField(default=0, help_text='Total cost of the subscription.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='app.parkinglot')),
            ],
        ),
    ]
