# Generated by Django 5.1 on 2025-01-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed',
            name='parking_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.parkinglot'),
        ),
    ]
