# Generated by Django 5.1 on 2025-01-17 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_subscribed_parking_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed',
            name='parking_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.parkingspace'),
        ),
        migrations.AlterField(
            model_name='subscribed',
            name='plate',
            field=models.CharField(help_text='Car plate number (e.g., AAA 000 A).', max_length=9, validators=[django.core.validators.RegexValidator(message='Plate number needd to be formated like AAA 000 A', regex='^[A-Z]{3} [0-9]{3} [A-Z]$')]),
        ),
    ]
